In [1]:
from tensorflow import keras

In [23]:
model = keras.Sequential(
    keras.layers.Dense(20, activation="sigmoid", input_shape=(9,)),
    keras.layers.Dense(7, activation="sigmoid")
)

In [39]:
model.compile(
    optimizer="adam",
    loss = "sparse_categorical_crossentropy",
    metrics = ["recall"]
)

In [40]:
import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt

In [41]:
df = pd.read_csv("../data/wine-model-training-data.csv")
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.5,0.14,0.34,1.3,0.055,50.0,153.0,0.99450,3.29,0.80,9.6,6.0
1,6.8,0.32,0.32,8.7,0.029,31.0,105.0,0.99146,3.00,0.34,12.3,7.0
2,7.5,0.28,0.34,4.2,0.028,36.0,116.0,0.99100,2.99,0.41,12.3,8.0
3,6.5,0.24,0.32,7.6,0.038,48.0,203.0,0.99580,3.45,0.54,9.7,7.0
4,6.9,0.21,0.62,6.3,0.042,7.0,109.0,0.99358,2.96,0.59,10.2,6.0

In [42]:
df2 = df
df2 = df2[df2['fixed acidity'] < 13]
df2 = df2[df2['residual sugar'] < 60]
df2 = df2[df2['chlorides'] < 0.3]
df2 = df2[df2['citric acid'] < 1.1]
df2.reset_index(drop=True, inplace=True)
df2.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.5,0.14,0.34,1.3,0.055,50.0,153.0,0.99450,3.29,0.80,9.6,6.0
1,6.8,0.32,0.32,8.7,0.029,31.0,105.0,0.99146,3.00,0.34,12.3,7.0
2,7.5,0.28,0.34,4.2,0.028,36.0,116.0,0.99100,2.99,0.41,12.3,8.0
3,6.5,0.24,0.32,7.6,0.038,48.0,203.0,0.99580,3.45,0.54,9.7,7.0
4,6.9,0.21,0.62,6.3,0.042,7.0,109.0,0.99358,2.96,0.59,10.2,6.0

In [43]:
def preprocess3d(dataframe):
    dataframe["densit_alcohol"] = dataframe["density"]/dataframe['alcohol']
    dataframe.drop("sulphates",axis=1, inplace=True)
    dataframe.drop("density",axis=1, inplace=True)
    dataframe.drop("chlorides",axis=1, inplace=True)
    pass

In [44]:
df3 = df2.copy()
preprocess3d(df3)
df3.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,free sulfur dioxide,total sulfur dioxide,pH,alcohol,quality,densit_alcohol
0,7.5,0.14,0.34,1.3,50.0,153.0,3.29,9.6,6.0,0.103594
1,6.8,0.32,0.32,8.7,31.0,105.0,3.00,12.3,7.0,0.080607
2,7.5,0.28,0.34,4.2,36.0,116.0,2.99,12.3,8.0,0.080569
3,6.5,0.24,0.32,7.6,48.0,203.0,3.45,9.7,7.0,0.102660
4,6.9,0.21,0.62,6.3,7.0,109.0,2.96,10.2,6.0,0.097410

In [45]:
df3.shape

(4158, 10)

In [46]:
X = df3.drop("quality", axis=True)
y = df3.quality
X.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,free sulfur dioxide,total sulfur dioxide,pH,alcohol,densit_alcohol
0,7.5,0.14,0.34,1.3,50.0,153.0,3.29,9.6,0.103594
1,6.8,0.32,0.32,8.7,31.0,105.0,3.00,12.3,0.080607
2,7.5,0.28,0.34,4.2,36.0,116.0,2.99,12.3,0.080569
3,6.5,0.24,0.32,7.6,48.0,203.0,3.45,9.7,0.102660
4,6.9,0.21,0.62,6.3,7.0,109.0,2.96,10.2,0.097410

In [47]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

In [48]:
X = scaler.fit_transform(X)

In [49]:
y.values, X

(array([6., 7., 8., ..., 6., 7., 6.]),
 array([[0.4625    , 0.05882353, 0.34      , ..., 0.51818182, 0.25806452,
         0.62325321],
        [0.375     , 0.23529412, 0.32      , ..., 0.25454545, 0.69354839,
         0.2022593 ],
        [0.4625    , 0.19607843, 0.34      , ..., 0.24545455, 0.69354839,
         0.20157438],
        ...,
        [0.4875    , 0.25490196, 0.27      , ..., 0.33636364, 0.19354839,
         0.71051957],
        [0.2875    , 0.15686275, 0.26      , ..., 0.42727273, 0.62903226,
         0.25009579],
        [0.3       , 0.16666667, 0.39      , ..., 0.46363636, 0.5       ,
         0.36043461]]))

In [51]:
model.fit(X, y)

TypeError: in user code:

    File "C:\Users\Ephraim\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\engine\training.py", line 1021, in train_function  *
        return step_function(self, iterator)
    File "C:\Users\Ephraim\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\engine\training.py", line 1010, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\Ephraim\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\engine\training.py", line 1000, in run_step  **
        outputs = model.train_step(data)
    File "C:\Users\Ephraim\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\engine\training.py", line 859, in train_step
        y_pred = self(x, training=True)
    File "C:\Users\Ephraim\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "C:\Users\Ephraim\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\engine\base_layer.py", line 2501, in _name_scope
        name_scope += '/'

    TypeError: unsupported operand type(s) for +=: 'Dense' and 'str'